#!/usr/bin/env python3
"""
Setup script to securely configure environment variables for FIBO Video Director.
This script helps you set up your API keys without exposing them in the repository.
"""

import os
import sys
from pathlib import Path

def setup_env():
    """Setup environment variables interactively."""
    env_file = Path(".env")
    env_example = Path(".env.example")
    
    print("🔐 FIBO Video Director Environment Setup")
    print("=" * 50)
    
    # Read the example file to get the template
    if not env_example.exists():
        print("❌ .env.example file not found!")
        return False
    
    with open(env_example, 'r') as f:
        example_content = f.read()
    
    print("This script will help you set up your environment variables.")
    print("Your API keys will be stored locally in .env and NOT committed to Git.\n")
    
    # Get API keys from user
    google_api_key = input("Enter your Google Gemini API Key: ").strip()
    if not google_api_key:
        print("❌ Google API Key is required!")
        return False
    
    fal_api_key = input("Enter your FAL.ai API Key: ").strip()
    if not fal_api_key:
        print("❌ FAL API Key is required!")
        return False
    
    # Optional AWS settings
    print("\n🔧 Optional AWS Settings (press Enter to skip):")
    s3_bucket = input("S3 Bucket name (default: fibo-frames-cache): ").strip() or "fibo-frames-cache"
    aws_access_key = input("AWS Access Key ID (optional): ").strip()
    aws_secret_key = input("AWS Secret Access Key (optional): ").strip()
    aws_region = input("AWS Region (default: us-east-1): ").strip() or "us-east-1"
    
    # Optional enhanced director
    use_enhanced = input("Use enhanced multi-agent director? (y/N): ").strip().lower()
    use_enhanced_director = "true" if use_enhanced in ['y', 'yes'] else "false"
    
    # Create .env content
    env_content = f"""# FIBO Video Director Environment Variables
# Generated by setup-env.py - DO NOT COMMIT THIS FILE

# Required: Google Gemini API Key for VLM
GOOGLE_API_KEY={google_api_key}

# Required: FAL.ai API Key for image generation
FAL_KEY={fal_api_key}

# Optional: S3 bucket for frame caching (auto-created if not exists)
FIBO_S3_BUCKET={s3_bucket}

# Optional: AWS credentials (use IAM roles in production)
AWS_ACCESS_KEY_ID={aws_access_key}
AWS_SECRET_ACCESS_KEY={aws_secret_key}
AWS_DEFAULT_REGION={aws_region}

# Optional: Enable enhanced multi-agent director
USE_ENHANCED_DIRECTOR={use_enhanced_director}
"""
    
    # Write .env file
    with open(env_file, 'w') as f:
        f.write(env_content)
    
    print(f"\n✅ Environment variables saved to {env_file}")
    print("🔒 This file is already in .gitignore and will not be committed to Git.")
    print("\n🚀 You can now run your FIBO Video Director application!")
    
    return True

if __name__ == "__main__":
    if setup_env():
        sys.exit(0)
    else:
        sys.exit(1)