#!/usr/bin/env python3
"""
FIBO Integration Service

Integrates with the existing FIBO generate.py script to create images
from structured JSON prompts generated by the AI Director.
"""

import os
import json
import subprocess
import asyncio
from pathlib import Path
from typing import Dict, Optional, Tuple
import tempfile
import shutil

class FIBOIntegration:
    """Integration service for FIBO image generation."""
    
    def __init__(self, fibo_root_path: str = "."):
        """Initialize FIBO integration.
        
        Args:
            fibo_root_path: Path to the FIBO project root directory
        """
        self.fibo_root = Path(fibo_root_path)
        self.generate_script = self.fibo_root / "generate.py"
        self.output_dir = self.fibo_root / "examples" / "outputs"
        
        # Ensure output directory exists
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        # Check if FIBO is available
        if not self.generate_script.exists():
            raise FileNotFoundError(f"FIBO generate.py not found at {self.generate_script}")
    
    async def generate_image_from_json(
        self, 
        structured_prompt: Dict, 
        output_name: str,
        seed: Optional[int] = None,
        enable_teacache: bool = True,
        model_mode: str = "gemini"
    ) -> Tuple[str, str]:
        """Generate an image using FIBO with a structured JSON prompt.
        
        Args:
            structured_prompt: The FIBO structured JSON prompt
            output_name: Name for the output files (without extension)
            seed: Random seed for reproducible generation
            enable_teacache: Whether to enable TeaCache for faster inference
            model_mode: VLM mode ("gemini" or "local")
            
        Returns:
            Tuple of (image_path, json_path) for the generated files
        """
        try:
            # Create temporary JSON file for the structured prompt
            with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
                json.dump(structured_prompt, f, indent=2)
                temp_json_path = f.name
            
            # Prepare FIBO command
            cmd = [
                "python", str(self.generate_script),
                "--structured-prompt", temp_json_path,
                "--output-dir", str(self.output_dir),
                "--output-name", output_name,
                "--model-mode", model_mode
            ]
            
            if seed is not None:
                cmd.extend(["--seed", str(seed)])
            
            if enable_teacache:
                cmd.append("--enable-teacache")
            
            # Set environment variables
            env = os.environ.copy()
            env["PYTHONPATH"] = f"{env.get('PYTHONPATH', '')}:{self.fibo_root}"
            
            # Run FIBO generation
            print(f"Running FIBO command: {' '.join(cmd)}")
            
            process = await asyncio.create_subprocess_exec(
                *cmd,
                cwd=self.fibo_root,
                env=env,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            
            stdout, stderr = await process.communicate()
            
            # Clean up temporary file
            os.unlink(temp_json_path)
            
            if process.returncode != 0:
                error_msg = stderr.decode() if stderr else "Unknown error"
                raise RuntimeError(f"FIBO generation failed: {error_msg}")
            
            # Find generated files
            image_path = self.output_dir / f"{output_name}.png"
            json_path = self.output_dir / f"{output_name}.json"
            
            if not image_path.exists():
                raise FileNotFoundError(f"Generated image not found: {image_path}")
            
            return str(image_path), str(json_path)
            
        except Exception as e:
            print(f"Error in FIBO generation: {e}")
            raise
    
    async def generate_checkpoint_frames(
        self,
        start_frame_prompt: Dict,
        end_frame_prompt: Dict,
        checkpoint_id: int,
        project_id: str,
        seed: Optional[int] = None
    ) -> Dict[str, str]:
        """Generate both start and end frames for a checkpoint.
        
        Args:
            start_frame_prompt: FIBO structured prompt for start frame
            end_frame_prompt: FIBO structured prompt for end frame
            checkpoint_id: The checkpoint ID
            project_id: The project ID
            seed: Random seed for reproducible generation
            
        Returns:
            Dictionary with paths to generated files
        """
        try:
            # Generate start frame
            start_name = f"project_{project_id}_checkpoint_{checkpoint_id}_start"
            start_seed = seed if seed is not None else checkpoint_id * 1000
            
            start_image, start_json = await self.generate_image_from_json(
                start_frame_prompt,
                start_name,
                seed=start_seed
            )
            
            # Generate end frame
            end_name = f"project_{project_id}_checkpoint_{checkpoint_id}_end"
            end_seed = seed if seed is not None else checkpoint_id * 1000 + 1
            
            end_image, end_json = await self.generate_image_from_json(
                end_frame_prompt,
                end_name,
                seed=end_seed
            )
            
            return {
                "start_frame_image": start_image,
                "start_frame_json": start_json,
                "end_frame_image": end_image,
                "end_frame_json": end_json
            }
            
        except Exception as e:
            print(f"Error generating checkpoint frames: {e}")
            raise
    
    def get_available_models(self) -> Dict[str, str]:
        """Get available FIBO models and modes.
        
        Returns:
            Dictionary of available models and their descriptions
        """
        return {
            "gemini": "Gemini VLM for prompt expansion (default)",
            "local": "Local FIBO-VLM for prompt expansion",
        }
    
    def check_fibo_status(self) -> Dict[str, bool]:
        """Check FIBO installation and dependencies.
        
        Returns:
            Dictionary with status of various FIBO components
        """
        status = {}
        
        # Check if generate.py exists
        status["generate_script"] = self.generate_script.exists()
        
        # Check if src directory exists
        status["src_directory"] = (self.fibo_root / "src").exists()
        
        # Check if output directory is writable
        try:
            test_file = self.output_dir / "test_write.tmp"
            test_file.touch()
            test_file.unlink()
            status["output_writable"] = True
        except:
            status["output_writable"] = False
        
        # Check environment variables
        status["google_api_key"] = bool(os.environ.get("GOOGLE_API_KEY"))
        status["pythonpath"] = str(self.fibo_root) in os.environ.get("PYTHONPATH", "")
        
        return status

# Global FIBO integration instance
fibo_integration = None

def get_fibo_integration() -> FIBOIntegration:
    """Get or create the global FIBO integration instance."""
    global fibo_integration
    
    if fibo_integration is None:
        # Try to find FIBO root directory
        fibo_root = os.environ.get("FIBO_ROOT", ".")
        fibo_integration = FIBOIntegration(fibo_root)
    
    return fibo_integration