default_agent: src_main
agents:
  fibo-video-director:
    name: fibo-video-director
    entrypoint: src.main:app
    deployment_type: container
    runtime_type: null
    platform: linux/amd64
    container_runtime: null
    source_path: null
    aws:
      execution_role: null
      execution_role_auto_create: false
      account: '476114109859'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  src_main:
    name: src_main
    entrypoint: F:/Abin/FIBO-main/FIBO-main/agentcore_fibo_agent/src/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: F:\Abin\FIBO-main\FIBO-main\agentcore_fibo_agent
    aws:
      execution_role: arn:aws:iam::476114109859:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-719a4b3125
      execution_role_auto_create: false
      account: '476114109859'
      region: us-east-1
      ecr_repository: 476114109859.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-src_main
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: src_main-PQhMz74UaU
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:476114109859:runtime/src_main-PQhMz74UaU
      agent_session_id: 434c9914-01d4-4b01-90c9-ac2724845ca2
    codebuild:
      project_name: bedrock-agentcore-src_main-builder
      execution_role: arn:aws:iam::476114109859:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-719a4b3125
      source_bucket: bedrock-agentcore-codebuild-sources-476114109859-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
